FROM ros:jazzy-ros-base@sha256:386d06ec6d4188f731bae5678e07b4cb64a4e4d4152090c0bd1f881dcf7706f5
RUN apt-get update && apt-get install -y --no-install-recommends build-essential ros-jazzy-demo-nodes-py ros-jazzy-demo-nodes-cpp && rm -rf /var/lib/apt/lists/*
